name: Build and deploy Node.js app to Azure Web App - multi-tier-1

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies and build React app
        run: |
          cd frontend/react-crud
          npm install
          npm run build
          npm install -g serve
          echo "serve -s build" > start.sh
          chmod +x start.sh

      - name: Upload build folder
        uses: actions/upload-artifact@v4
        with:
          name: react-build
          path: |
            frontend/react-crud/build
            frontend/react-crud/start.sh

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: react-build

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_DC1C8613FE544E89A6966CB5331ECB2A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_630810C937D5447396A71DF42644F007 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_BC3CAA722E7B458EB14495CB5A74E867 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'multi-tier-1'
          slot-name: 'Production'
          package: .
